set(build_config_note "${CTEST_BINARY_DIRECTORY}/build-config.txt")

set(note_cache_variables
    CMAKE_AR
    CMAKE_BUILD_TYPE
    CMAKE_C_COMPILER
    CMAKE_C_COMPILER_AR
    CMAKE_C_COMPILER_ARCHITECTURE_ID
    CMAKE_C_COMPILER_FRONTEND_VARIANT
    CMAKE_C_COMPILER_ID
    CMAKE_C_COMPILER_LAUNCHER
    CMAKE_C_COMPILER_LINKER
    CMAKE_C_COMPILER_LINKER_FRONTEND_VARIANT
    CMAKE_C_COMPILER_LINKER_ID
    CMAKE_C_COMPILER_LINKER_VERSION
    CMAKE_C_COMPILER_RANLIB
    CMAKE_C_COMPILER_VERSION
    CMAKE_C_FLAGS
    CMAKE_C_FLAGS_DEBUG
    CMAKE_C_FLAGS_MINSIZEREL
    CMAKE_C_FLAGS_RELEASE
    CMAKE_C_FLAGS_RELWITHDEBINFO
    CMAKE_CXX_COMPILER
    CMAKE_CXX_COMPILER_AR
    CMAKE_CXX_COMPILER_ARCHITECTURE_ID
    CMAKE_CXX_COMPILER_FRONTEND_VARIANT
    CMAKE_CXX_COMPILER_ID
    CMAKE_CXX_COMPILER_LAUNCHER
    CMAKE_CXX_COMPILER_LINKER
    CMAKE_CXX_COMPILER_LINKER_FRONTEND_VARIANT
    CMAKE_CXX_COMPILER_LINKER_ID
    CMAKE_CXX_COMPILER_LINKER_VERSION
    CMAKE_CXX_COMPILER_RANLIB
    CMAKE_CXX_COMPILER_VERSION
    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_DEBUG
    CMAKE_CXX_FLAGS_MINSIZEREL
    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_CXX_FLAGS_RELWITHDEBINFO
    CMAKE_EXE_LINKER_FLAGS
    CMAKE_EXE_LINKER_FLAGS_DEBUG
    CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
    CMAKE_EXE_LINKER_FLAGS_RELEASE
    CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_GENERATOR
    CMAKE_HOST_SYSTEM_NAME
    CMAKE_HOST_SYSTEM_PROCESSOR
    CMAKE_HOST_SYSTEM_VERSION
    CMAKE_LINKER
    CMAKE_MODULE_LINKER_FLAGS
    CMAKE_NM
    CMAKE_OBJDUMP
    CMAKE_OSX_ARCHITECTURES
    CMAKE_OSX_DEPLOYMENT_TARGET
    CMAKE_OSX_SYSROOT
    CMAKE_RANLIB
    CMAKE_SHARED_LINKER_FLAGS
    CMAKE_STRIP
    CMAKE_SYSTEM_NAME
    CMAKE_SYSTEM_PROCESSOR
    CMAKE_SYSTEM_VERSION
)

load_cache(
    "${CTEST_BINARY_DIRECTORY}"
    READ_WITH_PREFIX cache_
    ${note_cache_variables}
)

include("${CTEST_BINARY_DIRECTORY}/CMakeFiles/${CMAKE_VERSION}/CMakeSystem.cmake" OPTIONAL)
include("${CTEST_BINARY_DIRECTORY}/CMakeFiles/${CMAKE_VERSION}/CMakeCCompiler.cmake" OPTIONAL)
include("${CTEST_BINARY_DIRECTORY}/CMakeFiles/${CMAKE_VERSION}/CMakeCXXCompiler.cmake" OPTIONAL)
set(note_rule_variables
    CMAKE_C_ARCHIVE_CREATE
    CMAKE_C_ARCHIVE_APPEND
    CMAKE_C_ARCHIVE_FINISH
    CMAKE_CXX_ARCHIVE_CREATE
    CMAKE_CXX_ARCHIVE_APPEND
    CMAKE_CXX_ARCHIVE_FINISH
)

function(append_note_variable name)
    if(DEFINED cache_${name})
        set(value "${cache_${name}}")
    else()
        set(value "${${name}}")
    endif()
    file(APPEND "${build_config_note}" "${name}=${value}\n")
endfunction()

file(WRITE "${build_config_note}" "CTEST_SITE=${CTEST_SITE}\n")
file(APPEND "${build_config_note}" "CTEST_BUILD_NAME=${CTEST_BUILD_NAME}\n")
file(APPEND "${build_config_note}" "CTEST_CMAKE_GENERATOR=${CTEST_CMAKE_GENERATOR}\n")
foreach(name IN LISTS note_cache_variables note_rule_variables)
    append_note_variable("${name}")
endforeach()

list(APPEND CTEST_NOTES_FILES "${build_config_note}")
