#!/usr/bin/env python3

import argparse
import importlib.util
import pathlib
import re
import shlex
import sys


def cmake_quote(value):
    return "[=[" + str(value).replace("]=]", "]=] ]=] [=[") + "]=]"


def test_name(command):
    parts = shlex.split(command)
    name = re.sub(r"[.]py$", "", parts[0])
    for arg in parts[1:]:
        arg_name = re.sub(r"^--", "", arg)
        arg_name = re.sub(r"[^A-Za-z0-9_]+", ".", arg_name).strip(".")
        if arg_name:
            name += "." + arg_name
    return name


def load_test_runner(script_dir):
    sys.path.insert(0, str(script_dir))
    test_runner_path = script_dir / "test_runner.py"
    spec = importlib.util.spec_from_file_location("bitcoin_functional_test_runner", test_runner_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_test(out, name, command, properties):
    out.write(f"add_test(NAME {cmake_quote(name)}\n")
    out.write("  COMMAND\n")
    for item in command:
        out.write(f"    {cmake_quote(item)}\n")
    out.write(")\n")
    out.write(f"set_tests_properties({cmake_quote(name)} PROPERTIES\n")
    for key, value in properties:
        out.write(f"  {key} {cmake_quote(value)}\n")
    out.write(")\n\n")


def main():
    parser = argparse.ArgumentParser(description="Generate CTest registrations for Bitcoin Core functional tests.")
    parser.add_argument("--python", required=True)
    parser.add_argument("--script-dir", required=True, type=pathlib.Path)
    parser.add_argument("--config-file", required=True, type=pathlib.Path)
    parser.add_argument("--cache-dir", required=True, type=pathlib.Path)
    parser.add_argument("--tmpdir", required=True, type=pathlib.Path)
    parser.add_argument("--timeout-factor", required=True)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--extended", action="store_true")
    args = parser.parse_args()

    runner = load_test_runner(args.script_dir)
    commands = list(runner.BASE_SCRIPTS)
    if args.extended:
        commands = list(runner.EXTENDED_SCRIPTS) + commands

    with args.output.open("w", encoding="utf8") as out:
        out.write("# Generated by generate-functional-tests.py. Do not edit.\n\n")
        write_test(
            out,
            "functional.create_cache",
            [
                args.python,
                args.script_dir / "create_cache.py",
                f"--configfile={args.config_file}",
                f"--cachedir={args.cache_dir}",
                f"--tmpdir={args.tmpdir / 'create_cache'}",
                "--portseed=1",
                f"--timeout-factor={args.timeout_factor}",
            ],
            [
                ("FIXTURES_SETUP", "functional_cache"),
                ("LABELS", "functional"),
                ("SKIP_RETURN_CODE", "77"),
                ("ENVIRONMENT", "PYTHON_GIL=1"),
            ],
        )

        for index, command in enumerate(commands, start=2):
            parts = shlex.split(command)
            script = parts[0]
            extra_args = parts[1:]
            name_without_prefix = test_name(command)
            write_test(
                out,
                "functional." + name_without_prefix,
                [
                    args.python,
                    args.script_dir / script,
                    *extra_args,
                    f"--configfile={args.config_file}",
                    f"--cachedir={args.cache_dir}",
                    f"--tmpdir={args.tmpdir / name_without_prefix}",
                    f"--portseed={index}",
                    f"--timeout-factor={args.timeout_factor}",
                ],
                [
                    ("FIXTURES_REQUIRED", "functional_cache"),
                    ("LABELS", "functional"),
                    ("SKIP_RETURN_CODE", "77"),
                    ("ENVIRONMENT", "PYTHON_GIL=1"),
                ],
            )


if __name__ == "__main__":
    main()
